<a href="https://colab.research.google.com/github/prachisingh19/CodeAlpha_iris-flower-classification_project/blob/main/Product_Reviews_Prediction_with_Multinomial_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

The multinomial Naive Bayes classifier is suitable for classification with discrete features(e.g., word counts for text classification).The multinomial distribution normally requires integer feature counts . However,in practice , fractional counts such as tf-idf may also work.

### IMPORT LIBRARY

In [ ]:
[] import pandas as pd

In [ ]:
[] import numpy as np

In [ ]:
[] import matplotlib.pyplot as plt

In [ ]:
[] import seaborn as sns

## IMPORT DATASET

In [ ]:
import pandas as pd
df = pd.read_csv('/Womens Clothing E-Commerce Reviews.csv (1) (2).zip')

In [ ]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.shape

(23486, 11)

## MISSING VALUES

Remove missing values in Reviews columns with No Reviews text

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN

In [ ]:
df['Review'].fillna("No Review",inplace=True)

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

### Define Target (y) and Feature(x)

In [ ]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [ ]:
x=df['Review']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

### TRAIN TEST SPLIT

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [ ]:
x=df['Review Text']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

## GET FEATURES TEXT CONVERSION TO TOKENS

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'yellow color', 'yes runs',
       'yoga pants'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'yellow color', 'yes runs',
       'yoga pants'], dtype=object)

In [ ]:
x=df['Review Text']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
y=df['Rating']

In [ ]:
x=df['Review Text']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 dress', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
df['Review Text'].fillna('', inplace=True)

In [ ]:
y=df['Rating']

In [ ]:
x=df['Review Text']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
x_train=cv.fit_transform(x_train)

In [ ]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'yellow color',
       'yoga pants', 'zipper little'], dtype=object)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_test =cv.fit_transform(x_test)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 dress', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# get model train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

## GET MODEL PREDICTION

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 5, 5, ..., 5, 1, 1])

## GET PROBABILITY OF EACH PREDICTED CLASS

In [ ]:
model.predict_proba(x_test)

array([[4.86338640e-01, 3.43759135e-01, 6.21990599e-02, 7.06001084e-02,
        3.71030561e-02],
       [1.92984510e-02, 2.47397646e-01, 6.48898263e-02, 2.47325146e-01,
        4.21088931e-01],
       [3.58272506e-02, 6.66058394e-02, 1.22262774e-01, 2.16180049e-01,
        5.59124088e-01],
       ...,
       [2.31980299e-02, 1.19215112e-02, 2.02158820e-01, 1.81743570e-01,
        5.80978068e-01],
       [9.75537679e-01, 1.43011678e-04, 2.47496593e-04, 1.15438158e-04,
        2.39563749e-02],
       [5.49974218e-01, 2.63783138e-02, 6.23926412e-03, 3.05064690e-01,
        1.12343514e-01]])

## GET MODEL EVALUATION

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  23   22   26   51  131]
 [  37   47   75   96  215]
 [  80   87  127  211  356]
 [ 184  106  176  354  703]
 [ 434  290  360  674 2181]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.03      0.09      0.05       253
           2       0.09      0.10      0.09       470
           3       0.17      0.15      0.16       861
           4       0.26      0.23      0.24      1523
           5       0.61      0.55      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.23      0.22      0.22      7046
weighted avg       0.42      0.39      0.40      7046



## RECATEGORIES RATING AS POOR(0) AND GOOD (1)

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [ ]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [ ]:
y=df['Rating']

In [ ]:
x=df['Review Text']

### TRAIN TEST SPLIT

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape


((16440,), (7046,), (16440,), (7046,))

### GET FEATURES TEXT CONVERSION TO TOKENS

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
x_train = cv.fit_transform(x_train)

In [ ]:
x_test=cv.fit_transform(x_test)

## GET MODEL RE-TRAIN

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

### GET MODEL PREDICTION

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
x_test=cv.transform(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

## GET MODEL EVALUATION

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 863  720]
 [ 483 4980]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.64      0.55      0.59      1583
           1       0.87      0.91      0.89      5463

    accuracy                           0.83      7046
   macro avg       0.76      0.73      0.74      7046
weighted avg       0.82      0.83      0.82      7046

